@startuml name TuringMachine

[*] --> PrepareInput

state PrepareInput {
    [*] --> MoveX

    state MoveX {
        [*] --> CopyT0ToT1
        CopyT0ToT1 --> CopyT0ToT1
        CopyT0ToT1 --> DeleteSeparator : if found
        DeleteSeparator --> [*]
    }

    MoveX --> MoveY

    state MoveY {
        [*] --> CopyT0ToT2
        CopyT0ToT2 --> CopyT0ToT2
        CopyT0ToT2 --> [*] : if end
    }

    MoveY --> Normalize

    state Normalize {
        [*] --> AddZerosToT1T2
        AddZerosToT1T2 --> AddZerosToT1T2RL
        AddZerosToT1T2RL --> [*] : if both blank
    }

    Normalize --> [*]

}

PrepareInput --> ChooseFormula

state ChooseFormula {
    [*] --> IterateT1T2LR
    IterateT1T2LR --> IterateT1T2LR
    IterateT1T2LR --> F1 : T1>T2
    IterateT1T2LR --> F2 : T2>T1
    IterateT1T2LR --> F2 : T1 blank

    F1 --> [*] : F1 chosen
    F2 --> [*] : F2 chosen
}

ChooseFormula --> Formula1 : if F1

state Formula1 {
    [*] --> PositionToROfT1T2
    PositionToROfT1T2 --> AddToT3
    
    AddToT3 --> PositionToROfT3

    PositionToROfT3 --> MultiplyBy2T3

    MultiplyBy2T3 --> PrintResultFromT3

    PrintResultFromT3 --> [*]
}

ChooseFormula --> Formula2 : if F2

state Formula2 {
    [*] --> PositionAllToR

    PositionAllToR --> CopyT2ToT3

    CopyT2ToT3 --> MoveBack

    MoveBack --> MultiplyT2AndT3

    state MultiplyT2AndT3 {
        [*] --> CheckT2

        CheckT2 --> MultiplyT3By2 : if T2==zero
        CheckT2 --> AddT3AndT4InT5 : if T2==one
        AddT3AndT4InT5 --> CopyT5ToT4 
        CopyT5ToT4 --> MultiplyT3By2

        MultiplyT3By2 --> CheckT2

        CheckT2 --> [*] : if T2==blank
    }

    MultiplyT2AndT3 --> AddT1ToT4

    AddT1ToT4 --> PrintResultFromT4

    PrintResultFromT4 --> [*]
}

Formula1 --> [*]
Formula2 --> [*]


@enduml