version: "3.9"

services:
  roachdb:
    image: cockroachdb/cockroach:v21.1.15
    restart: on-failure
    ports:
      - "26257:26257"
      - "8081:8080"
    volumes:
      - "/Users/killer/.math-proj:/cockroach/cockroach-data"
    command:
      - start-single-node
      - --insecure

  maid:
    build:
      context: math-maid
      dockerfile: Dockerfile
    depends_on:
      - roachdb
    ports:
      - "8080:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://roachdb:26257/postgres
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9090
  spa:
    build:
      context: maid-simp
      dockerfile: Dockerfile
    depends_on:
      - maid
    ports:
      - "80:80"
